### ISSUE TITLE
Hello world example not working

### ISSUE THREAD

**Issue by shevernitskiy** [littledivy/wgui#11]
Hey! I'm trying to make hello-world example work https://github.com/littledivy/wgui/tree/main/wgui-examples/hello-world

I getting this output:
```shell
deno run -A --unstable-ffi --unstable-webgpu wgui.tsx

SDL2 initialized on Windows
error: Uncaught (in promise) TypeError: Must be a file URL.
      code: Deno.readTextFileSync(rectWgsl),
                 ^
    at pathFromURL (ext:deno_web/00_infra.js:447:13)
    at Object.readTextFileSync (ext:deno_fs/30_fs.js:832:36)
    at new RectRenderer (https://raw.githubusercontent.com/littledivy/wgui/main/renderer.ts:32:18)
    at new Renderer (https://raw.githubusercontent.com/littledivy/wgui/main/renderer.ts:334:25)
    at Function.initialize (https://raw.githubusercontent.com/littledivy/wgui/main/app.ts:59:22)
    at eventLoopTick (ext:core/01_core.js:64:7)
```

win11, all sdl binaries and wgui.wgsl in cwd, deno 1.40.3

**Comment by jabed-web-dev** [comment]
**I have the same problem.**

```
deno run -A --unstable-webgpu src/main.tsx
SDL2 initialized on Windows
error: Uncaught (in promise) NotFound: The system cannot find the file specified. (os error 2): readfile './Inter.ttf': The system cannot find the file specified. (os error 2): readfile './Inter.ttf': The system cannot find the file specified. (os error 2)
    const buffer = Deno.readFileSync(`${outputDir}${fileName}.ttf`);
                        ^
    at Object.readFileSync (ext:deno_fs/30_fs.js:739:10)
    at loadFont (https://jsr.io/@divy/wgui/0.2.0/text.ts:166:25)
    at async https://jsr.io/@divy/wgui/0.2.0/mod.ts:44:1
```

**Comment by AnNingUI** [comment]
Go to [here](https://github.com/rsms/inter/releases) and unzip `InterVariable.ttf` to the project root directory and rename it to `Inter.ttf`,But now a new bug has appeared

```
deno run -A --unstable-webgpu main.tsx

SDL2_image not loaded. Some features will not be available.
SDL2_ttf not loaded. Some features will not be available.
SDL2 initialized on Windows
SDL2_image not loaded. Some features will not be available.
SDL2_ttf not loaded. Some features will not be available.
SDL2 initialized on Windows
error: Uncaught (in promise) TypeError: is not an object
        return new Deno.UnsafeWindowSurface("win32", window, hinstance);
               ^
    at Window.windowSurface (https://jsr.io/@divy/sdl2/0.10.1/mod.ts:1274:16)
    at InnerApp.initialize (https://jsr.io/@divy/wgui/0.2.0/app.ts:45:28)
    at eventLoopTick (ext:core/01_core.js:179:7)
    at async render (https://jsr.io/@divy/wgui/0.2.0/mod.ts:80:15)
```

ls
```css
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          2025/8/3     15:29                .zed
-a----          2025/8/3     17:19            396 deno.json
-a----          2025/8/3     17:30          27582 deno.lock
-a----          2025/8/3     17:15       67108864 Inter.bin
-a----          2025/8/3     17:15        3683853 Inter.png
-a----        2024/11/15     16:16         879708 Inter.ttf
-a----          2025/8/3     17:24            655 main.tsx
-a----          2025/6/2     23:18        1576448 SDL2.dll
```
